services:
  db:
    image: mysql:8.0
    container_name: projeto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: projeto_db
    ports:
      - "3306:3306"
    volumes:
      - meus-dados-mysql:/var/lib/mysql
      - ./logs:/logs
      - ./scripts:/scripts

volumes:
  meus-dados-mysql: